# Generated by Django 5.1.4 on 2025-01-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_meals_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meals',
            name='ratio',
            field=models.IntegerField(default=0),
        ),
    ]
