# Generated by Django 5.1.4 on 2025-01-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meals_num_ratings_meals_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='num_ratings',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meals',
            name='ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
