# Generated by Django 5.1.4 on 2025-01-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meals_num_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='num_ratings',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='ratio',
        ),
    ]
